# Generated by Django 2.2 on 2019-05-02 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, db_index=True),
        ),
    ]
