# Generated by Django 2.2 on 2019-05-02 16:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190502_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, db_index=True),
        ),
    ]
