# Generated by Django 2.2 on 2019-05-12 11:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
        migrations.RemoveField(
            model_name='product',
            name='body',
        ),
        migrations.AddField(
            model_name='about',
            name='body1',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='about',
            name='body2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='product',
            name='body1',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='product',
            name='body2',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='SOME STRING'),
        ),
    ]
